// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1d14b597-2166-4c0f-8838-6afe47f6cc09",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_gzPV3UIk5",
    "aws_user_pools_web_client_id": "6r3bmn6g0pj9hk2ppjtofg2ed",
    "oauth": {}
};


export default awsmobile;
